import type { Metadata } from "next";
import NextAuthProvider from "@/providers/NextAuthProvider";
import ThemeRegistry from "@/styles/themes/ThemeRegistry";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <NextAuthProvider>
          <ThemeRegistry>{children}</ThemeRegistry>
        </NextAuthProvider>
      </body>
    </html>
  );
}
